version: "3.3"

networks:
  net:
    driver: bridge

services:
  # database
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: priroda
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: MyPWD56821
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: 'postgres-priroda'
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d priroda"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net
  # service
  app:
    image: "ubuntu"
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 4G
    container_name: 'app-priroda'
    restart: unless-stopped
    hostname: server
    environment:
      DATABASE_URL: postgres://admin:MyPWD56821@postgres-priroda:5432/priroda?sslmode=disable # должно быть в секретах/конфиге. Учебный пример
    ports:
      - 8080:8080
      # - 8090:8090
    command: ./app
    depends_on:
      - postgres
    networks:
      - net

  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: stage
      MYSQL_USER: example
      MYSQL_PASSWORD: secret2
    volumes:
      - ./dbdata:/var/lib/mysql/