// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package queries

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddAnnouncement(ctx context.Context, arg AddAnnouncementParams) (sql.Result, error)
	AddPhoto(ctx context.Context, arg AddPhotoParams) error
	Ban(ctx context.Context, tgid sql.NullInt64) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetAnnId(ctx context.Context, tgid sql.NullInt64) (sql.NullInt64, error)
	GetAnnouncement(ctx context.Context, arg GetAnnouncementParams) (GetAnnouncementRow, error)
	GetAnnouncementOnAdmMsgID(ctx context.Context, admmsgid sql.NullInt64) (GetAnnouncementOnAdmMsgIDRow, error)
	GetStatus(ctx context.Context, tgid sql.NullInt64) (sql.NullInt64, error)
	GetUserInfo(ctx context.Context, tgid sql.NullInt64) (GetUserInfoRow, error)
	SetAdminMsgID(ctx context.Context, arg SetAdminMsgIDParams) error
	SetPublicID(ctx context.Context, arg SetPublicIDParams) error
	SetStatus(ctx context.Context, arg SetStatusParams) error
	UnBan(ctx context.Context, tgid sql.NullInt64) error
}

var _ Querier = (*Queries)(nil)
